### ISSUE TITLE
Please provide AppImage for download

### ISSUE THREAD

**Issue by probonopd** [teriflix/scrite#157]
Please provide AppImage for download rather than a .tar.gz containing an AppImage.
For the reasons please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages/cc2441518975caca23e9ce2dba6f08a22c678d1e#common-mistake.

I would like to add Scrite to https://appimage.github.io/ but that requires the AppImage to be directly downloadable.

**Comment by pnudupa** [comment]
@probonopd - The package script for Linux has now been updated to generate AppImage instead of a tar.gz. AppImage of 0.4.13-beta is now available for download from https://www.scrite.io/index.php/download-linux/

I have checked the AppImage on Ubuntu 20.04 and 16.04 and also on KUbuntu 18.04. Let me know when you have had a chance to check it as well. We can close this issue after that.

**Comment by probonopd** [comment]
Excellent :+1:  thank you very much. Works a treat.
