### ISSUE TITLE
[0.6.4 All] High Memory Footprint In Structure Canvas

### ISSUE THREAD

**Issue by teriflix** [teriflix/scrite#220]
Bug reported by Harpreet on the Forum: 
> version 0.6.4 Beta > Structure tab is taking lots of memory and my laptop hanged on launching itself.  I've tried 3 times, but it's too long to load the structure tab. 

https://www.scrite.io/index.php/forum/topic/memory-footprint-very-high-on-0-6-4-beta/

**Comment by pnudupa** [comment]
When I load a screenplay with about 230 scenes spread across 5 episodes, this is the memory consumption I notice.

<img width="559" alt="image" src="https://user-images.githubusercontent.com/8263701/117653305-d8d38280-b1b1-11eb-946e-094dace435eb.png">

The memory consumption is rather high.

**Comment by pnudupa** [comment]
Rather than load each index card in full detail, we now load only a limited detail for every index card, until keyboard focus is assigned to it, at which point we load the full index card. This is enabled by using a custom QML loader called LodLoader. By using LodLoader, memory consumption was slashed by 3.4 times!!

<img width="559" alt="image" src="https://user-images.githubusercontent.com/8263701/117653692-5ac3ab80-b1b2-11eb-834d-77ce3f0cf171.png">

**Comment by teriflix** [comment]
On Windows also, we notice 4.3x reduction in memory.

before:

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/63646106/117661630-3bca1700-b1bc-11eb-8bd2-58ffb4bb3874.png">

after:

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/63646106/117661297-cfe7ae80-b1bb-11eb-8082-e7857ba8bac0.png">

**Comment by pnudupa** [comment]
Harpreeth confirmed that this issue is now resolved for him: (https://www.scrite.io/index.php/forum/topic/memory-footprint-very-high-on-0-6-4-beta/#postid-479)
