### ISSUE TITLE
[0.8.5-All]: Hyphen is getting added at the end of scene titles during PDF export, but not during display.

### ISSUE THREAD

**Issue by gouthampkanade** [teriflix/scrite#275]

**Comment by gouthampkanade** [comment]
Windows - App Version 0.8.5-beta-x64

**Comment by gouthampkanade** [comment]
![2](https://user-images.githubusercontent.com/97776972/149610392-883f7948-6d4e-49b0-9aab-6bb3e3f62f52.png)
![1](https://user-images.githubusercontent.com/97776972/149610394-4b8740e5-7973-4a75-ab69-a3176de2d0eb.jpg)

**Comment by pnudupa** [comment]
We toyed around with a few options and finally settled on this format for scene heading. A scene heading has 3 fiends to it.

[Field-1]. [Field-2] - [Field-3]

Field-1 is INT, EXT or I/E.
Field-2 is location name
Field-3 is time (DAY, NIGHT, LATER, etc..)

If Field-3 isn't present, then it means that its the same time as the previous scene. But we do retain the - there.

I do notice and acknowledge the bug here. There should ideally be a - at the end of scene heading in the UI also.

I guess the title of this bug needs to be changed. We have to show a - in the scene heading also, so that it sticks to one convention.
