### ISSUE TITLE
0.8.5-beta-x64: Exporting to PDF with "Print each scene on a new page" option adds a blank page between each scene

### ISSUE THREAD

**Issue by gouthampkanade** [teriflix/scrite#276]
![3__01](https://user-images.githubusercontent.com/97776972/149610550-520dac26-1414-4ebc-bb14-c8f654ab8a72.jpg)

**Comment by pnudupa** [comment]
I suppose you have empty lines at the end of the scene, which will obviously spill over to the next page. We don't crop lines, simply because its at the end. Word doesnt crop lines either.

I tried reproducing this, doesnt happen on any of my scripts. If you can reproduce this issue on a screenplay from Scriptalay, maybe we can look into it as an issue.
