### ISSUE TITLE
[0.8.8 - beta - x64] New scene (Ctrl+Shift+N) -> Cursor goes to the first line in the new scene. Press the up arrow. Cursor goes to the end of the last line in the previous scene. Press Down key again. Cursor goes to the first line in the new scene. In all these 3 actions, the cursor should go to the new scene title.

### ISSUE THREAD

**Issue by gouthampkanade** [teriflix/scrite#277]

**Comment by pnudupa** [comment]
Scrite's UI is scene centric and it treats Scene-Heading distinctly from rest of the scene text. To edit scene heading you can either click on the heading or use keyboard shortcut Cmd+0 or Ctrl+0. As such the cursor does not flow through the heading. This is by intent, because of how we have envisioned the UI to be.
