### ISSUE TITLE
[0.4.0] ಕನ್ನಡ ಟೈಪಿಂಗ್ ನಲ್ಲಿ ನುಡಿ ರೀತಿ ಕೀಬೋರ್ಡ್ ಸ್ಟಿಂಗ್ ಇದ್ರೆ ಉತ್ಥಮ

### ISSUE THREAD

**Issue by teriflix** [teriflix/scrite#94]

**Comment by rghv** [comment]
Would it not be better to delegate that to common input engines/tools (Nudi, Baraha etc)  that already provide indic input via various popular means (inscript, kg-ga-pa, phonetic like Baraha etc). As long as Scrite supports unicode fonts and is able to work with those input engines, it should work well.

Doing all of Indic input within Scrite would mean lot of effort reinventing a solution, for an already solved problem.

**Comment by pnudupa** [comment]
@rghv - It's already possible to use IME with Scrite. Many of our users use Pada, Baraha and even the built in keyboard IMEs on macOS with Scrite.

![built-in-ime](https://user-images.githubusercontent.com/8263701/87303828-6bbf7400-c531-11ea-8301-9c3574281fa2.jpg)

Within Scrite, we want to improve the transliterator so that users can configure their Scrite instance to switch to Hindi or Kannada for dialogues, but English for Action and other elements.

**Comment by pnudupa** [comment]
@rghv - you can now use input methods from your operating system within Scrite.

https://www.scrite.io/index.php/using-input-methods/
